---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: peopledoc.java
      vars:
        devsecops_ca_enabled: false
    - role: ansible-role-jmx-datadog
      vars:
        jmx_instances:
          - user: jmxuser
            password: test123abc
            port: 7199
            name: app-test-instance
        jvm_user: testuser
        jvm_group: testuser

        other_datadog_checks:
          test:
            name: test

        datadog_api_key: apikey
        datadog_version: "6.8.0"
        datadog_java_integration: false
        datadog_config:
          tags: env:testing
