---
- name: Set jmx_instances when using direct parameters
  set_fact:
    jmx_instances:
      - user: "{{ user }}"
        password: "{{ password }}"
        port: "{{ jmx_port }}"
        name: "{{ app_instance_name }}"
  when: jmx_instances is not defined
  no_log: true

- name: Set canonical datadog agent version
  set_fact:
    datadog_version: "{{ datadog_agent_version|regex_search('(\\d+\\.\\d+\\.\\d+)') }}"
  when: datadog_agent_version is defined and datadog_version is not defined

- name: Set datadog package version
  include_vars: "{{ ansible_os_family }}.yml"
  when: datadog_version is defined and datadog_agent_version is not defined

# https://github.com/DataDog/datadog-agent/blob/master/docs/agent/hostname-resolution.md
- name: Set datadog_config
  set_fact:
    datadog_config: "{{ datadog_config | combine(hostname_fqdn_config|default({})) }}"
  vars:
    hostname_fqdn_config:
      hostname: "{{ ansible_fqdn if datadog_version is version_compare('6.0.0', '>=') and datadog_version is version_compare('6.3.0', '<') else '' }}"
      hostname_fqdn: true

- name: Include role Datadog.datadog
  import_role:
    name: Datadog.datadog
  vars:
    jmx_check_config:
      jmx:
        init_config:
        instances: "{{ jmx_instances|map('combine', {'host': 'localhost'})|list  }}"
    datadog_checks: "{{ other_datadog_checks|combine(jmx_check_config) }}"
  tags: datadog_agent

- name: group {{ jvm_user }}
  group:
    name: "{{ jvm_group }}"
    gid: "{{ jvm_group_id|default(omit) }}"
    state: present

- name: user {{ jvm_user }}
  user:
    name: "{{ jvm_user }}"
    group: "{{ jvm_group }}"
    uid: "{{ jvm_user_id|default(omit) }}"
    state: present

- name: Get JAVA_HOME
  shell: . /etc/profile && echo $JAVA_HOME
  register: java_path
  changed_when: false

- name: Redefine java_path if JAVA_HOME is defined
  set_fact:
    JAVA_HOME: '{{ java_path.stdout }}'
  when: java_path.stdout is defined and java_path.stdout != ""

- name: Stat /etc/alternatives/java
  stat:
    path: /etc/alternatives/java
  when: java_path.stdout is not defined or java_path.stdout == ""
  register: alternatives_java_path

- name: Get JAVA_HOME path from java bin path
  set_fact:
    JAVA_HOME: "{{ alternatives_java_path.replace('/bin/java', '') }}"
  when: java_path.stdout is not defined or java_path.stdout == ""

- name: Stat $JAVA_HOME/jre/lib/management
  stat:
    path: "{{ JAVA_HOME }}/jre/lib/management/"
  register: java_path_test

- name: Test $JAVA_HOME/jre/lib/management existence
  fail:
    msg: "JRE directory not found."
  when: not java_path_test.stat.exists

- vars:
    management_path: "{{ JAVA_HOME }}/jre/lib/management/"
  block:
    - name: username/password in jmxremote.password
      lineinfile:
        path: "{{ management_path }}/jmxremote.password"
        line: "{{ item.user }} {{ item.password }}"
        owner: "{{ jvm_user }}"
        group: "{{ jvm_group }}"
        mode: 0600
        create: true
        state: present
      with_items: "{{ jmx_instances }}"
      no_log: true


    - name: username/role in jmxremote.access
      lineinfile:
        path: "{{ management_path }}/jmxremote.access"
        line: "{{ item.user }} readonly"
        owner: "{{ jvm_user }}"
        group: "{{ jvm_group }}"
        create: true
        state: present
      with_items: "{{ jmx_instances }}"
      no_log: true

    # In case the files are symlinks (for ex. on Debian with OpenJDK or multiple JDKs)
    - name: Set ownership of jmxremote.password
      file:
        path: "{{ management_path }}/jmxremote.password"
        follow: true
        owner: "{{ jvm_user }}"
        group: "{{ jvm_group }}"
        mode: 0600

    - name: Set ownership of jmxremote.access
      file:
        path: "{{ management_path }}/jmxremote.access"
        follow: true
        owner: "{{ jvm_user }}"
        group: "{{ jvm_group }}"

- name: Add CA certificates
  apt:
    name: ca-certificates
    update_cache: true
    state: present

- name: Add java datadog agent for applicative traces
  get_url:
    url: "https://search.maven.org/classic/remote_content?g=com.datadoghq&a=dd-java-agent&v={{ datadog_java_agent_version }}"
    dest: /usr/local/bin/dd-java-agent.jar
  when: datadog_java_integration

- name: Register jvm options for DataDog as string
  set_fact:
    java_opts_datadog_jmx: "-Dcom.sun.management.jmxremote.port={{ item.port }}
      -Dcom.sun.management.jmxremote.ssl=false
      {%- if datadog_java_integration %} -javaagent:/usr/local/bin/dd-java-agent.jar{% endif %}
      -Ddd.service.name={{ item.name }}"
  with_items: "{{ jmx_instances }}"
  no_log: true

- name: Register jvm options for DataDog as list
  set_fact:
    java_opts_datadog_jmx_list: "{{ java_opts_datadog_jmx.split(' ') }}"
