---
platforms:
  - name: molecule_test_instance
    image: ${BASE_IMAGE:-debian:stretch}
scenario:
  name: java11
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check         # added to verify --check
    - side_effect
    - verify
    - destroy
