---
platforms:
  - name: molecule_test_instance
    image: ${BASE_IMAGE:-debian:stretch}
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # Uncomment this when the two failures with Datadog.datadog will be fixed
    # - idempotence
    - check         # added to verify --check
    - side_effect
    - verify
    - destroy
